name: "jest-reports"
branding:
  icon: "umbrella"
  color: "blue"
description: "test coverage reporter"
author: "vgrafe"
inputs:
  github-token:
    description: "A github access token"
    default: ${{ github.token }}
  cover-pr-changes-only:
    description: "Only run coverage on changes introduced in the PR"
    default: True
  run-steps:
    description: "skip any step by removing the corresponging item from this comma-separated list"
    default: "compare-with-base-branch,report-on-github,annotations-changes,annotations-all"
runs:
  using: composite
  steps:
    # forcing node 16.10.0 since later versions have memory issues with jest
    - uses: actions/setup-node@v3
      with:
        node-version: "16.10.0"

    # needed for cache to work https://github.com/crazy-max/ghaction-github-runtime
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2

    - run: DEFAULT_BRANCH=${{ github.event.repository.default_branch }} INPUT_RUN_STEPS=${{ inputs.run-steps }} INPUT_GITHUB_TOKEN=${{ inputs.github-token }} INPUT_COVER_PR_CHANGES_ONLY=${{ inputs.cover-pr-changes-only }} node ${{ github.action_path }}/dist/index.js
      shell: bash
